### ISSUE TITLE
Error: Could not resolve "a" for @virgilsecurity/e3kit-browser

### ISSUE THREAD

**Issue by thecannabisapp** [Menci/vite-plugin-wasm#59]
Trying to use @virgilsecurity/e3kit-browser with vite using this wasm plugin. Not sure if the problem is with the library I'm using which is https://github.com/VirgilSecurity/virgil-e3kit-js/ or with how I've configured the vite as I'm transitioning from Webpack 5 and React Rewired.

Here's a sandbox minimal reproduction: https://stackblitz.com/edit/vitejs-vite-jruc2f

```zsh
> vite-react-typescript-starter@0.0.0 dev
> vite


  VITE v5.3.5  ready in 2701 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
✘ [ERROR] Could not resolve "a"

    vite-plugin-wasm-namespace:/home/projects/vitejs-vite-jruc2f/node_modules/@virgilsecurity/e3kit-browser/dist/libpythia.browser.wasm:43:935:
      43 │ ... __vite__wasmImport_0_29, E as __vite__wasmImport_0_30 } from "a";
         ╵                                                                  ~~~

  You can mark the path "a" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.

✘ [ERROR] Could not resolve "a"

    vite-plugin-wasm-namespace:/home/projects/vitejs-vite-jruc2f/node_modules/@virgilsecurity/e3kit-browser/dist/libfoundation.browser.wasm:43:455:
      43 │ ... __vite__wasmImport_0_13, o as __vite__wasmImport_0_14 } from "a";
         ╵                                                                  ~~~

  You can mark the path "a" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.

Error: Build failed with 2 errors:
vite-plugin-wasm-namespace:/home/projects/vitejs-vite-jruc2f/node_modules/@virgilsecurity/e3kit-browser/dist/libfoundation.browser.wasm:43:455: ERROR: Could not resolve "a"
vite-plugin-wasm-namespace:/home/projects/vitejs-vite-jruc2f/node_modules/@virgilsecurity/e3kit-browser/dist/libpythia.browser.wasm:43:935: ERROR: Could not resolve "a"
    at failureErrorWithLog (/home/projects/vitejs-vite-jruc2f/node_modules/esbuild/lib/main.js:1462:15)
    at eval (/home/projects/vitejs-vite-jruc2f/node_modules/esbuild/lib/main.js:935:25)
    at eval (/home/projects/vitejs-vite-jruc2f/node_modules/esbuild/lib/main.js:1343:9) {
  errors: [Getter/Setter],
  warnings: [Getter/Setter]
}

Node.js 18.20.3

~/projects/vitejs-vite-jruc2f 10s
❯ vite

  VITE v5.3.5  ready in 2320 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
✘ [ERROR] Could not resolve "a"

    vite-plugin-wasm-namespace:/home/projects/vitejs-vite-jruc2f/node_modules/@virgilsecurity/e3kit-browser/dist/libpythia.browser.wasm:43:935:
      43 │ ... __vite__wasmImport_0_29, E as __vite__wasmImport_0_30 } from "a";
         ╵                                                                  ~~~

  You can mark the path "a" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.

✘ [ERROR] Could not resolve "a"

    vite-plugin-wasm-namespace:/home/projects/vitejs-vite-jruc2f/node_modules/@virgilsecurity/e3kit-browser/dist/libfoundation.browser.wasm:43:455:
      43 │ ... __vite__wasmImport_0_13, o as __vite__wasmImport_0_14 } from "a";
         ╵                                                                  ~~~

  You can mark the path "a" as external to exclude it from the bundle, which will remove this error and leave the unresolved path in the bundle.

Error: Build failed with 2 errors:
vite-plugin-wasm-namespace:/home/projects/vitejs-vite-jruc2f/node_modules/@virgilsecurity/e3kit-browser/dist/libfoundation.browser.wasm:43:455: ERROR: Could not resolve "a"
vite-plugin-wasm-namespace:/home/projects/vitejs-vite-jruc2f/node_modules/@virgilsecurity/e3kit-browser/dist/libpythia.browser.wasm:43:935: ERROR: Could not resolve "a"
    at failureErrorWithLog (/home/projects/vitejs-vite-jruc2f/node_modules/esbuild/lib/main.js:1462:15)
    at eval (/home/projects/vitejs-vite-jruc2f/node_modules/esbuild/lib/main.js:935:25)
    at eval (/home/projects/vitejs-vite-jruc2f/node_modules/esbuild/lib/main.js:1343:9) {
  errors: [Getter/Setter],
  warnings: [Getter/Setter]
}

Node.js 18.20.3
```

**Comment by Menci** [comment]
![image](https://github.com/user-attachments/assets/010d4185-ca0c-4e1b-909d-6500cfda342a)

This package is importing WASM as path, which means it's not an ES module WASM file. Keep in mind that this plugin is only for the https://github.com/WebAssembly/esm-integration specification. Please refer to Vite's native WASM handling for loading this WASM file.
