### ISSUE TITLE
Error when importing WASM

### ISSUE THREAD

**Issue by Yaron-Ha** [Menci/vite-plugin-wasm#8]
I'm importing the package '@dimforge/rapier2d', which contains WASM files.

My Vite config file:
```js
import { defineConfig } from 'vite'
import wasm from 'vite-plugin-wasm'
import topLevelAwait from 'vite-plugin-top-level-await'

export default defineConfig({
	plugins: [
		/**
		 * Since 2.x version of this plugin, the `filter` option has been removed.
		 *
		 * For 1.x (with Vite 2.x):
		 *   By default ALL `.wasm` imports will be transformed to WebAssembly ES module.
		 *   You can also set a filter (function or regex) to match files you want to transform.
		 *   Other files will fallback to Vite's default WASM loader (i.e. You need to call `initWasm()` for them).
		 *   ```js
		 *   wasm({
		 *     filter: /syntect_bg.wasm$/
		 *   })
		 *   ```
		 */
		wasm(),
		topLevelAwait(),
	],
    server: {
        port: 9001
    },
})
```
Error:
```js
X [ERROR] No loader is configured for ".wasm" files: node_modules/@dimforge/rapier2d/rapier_wasm2d_bg.wasm

    node_modules/@dimforge/rapier2d/rapier_wasm2d.js:1:22:
      1 │ import * as wasm from "./rapier_wasm2d_bg.wasm";
        ╵                       ~~~~~~~~~~~~~~~~~~~~~~~~~

C:\Users\yisha\Gits\Shuch\node_modules\esbuild\lib\main.js:1605
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 1 error:
node_modules/@dimforge/rapier2d/rapier_wasm2d.js:1:22: ERROR: No loader is configured for ".wasm" files: node_modules/@dimforge/rapier2d/rapier_wasm2d_bg.wasm
    at failureErrorWithLog (C:\Users\yisha\Gits\Shuch\node_modules\esbuild\lib\main.js:1605:15)
    at C:\Users\yisha\Gits\Shuch\node_modules\esbuild\lib\main.js:1251:28
    at runOnEndCallbacks (C:\Users\yisha\Gits\Shuch\node_modules\esbuild\lib\main.js:1034:63)
    at buildResponseToResult (C:\Users\yisha\Gits\Shuch\node_modules\esbuild\lib\main.js:1249:7)
    at C:\Users\yisha\Gits\Shuch\node_modules\esbuild\lib\main.js:1358:14
    at C:\Users\yisha\Gits\Shuch\node_modules\esbuild\lib\main.js:666:9
    at handleIncomingPacket (C:\Users\yisha\Gits\Shuch\node_modules\esbuild\lib\main.js:763:9)
    at Socket.readFromStdout (C:\Users\yisha\Gits\Shuch\node_modules\esbuild\lib\main.js:632:7)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 22,
        file: 'node_modules/@dimforge/rapier2d/rapier_wasm2d.js',
        length: 25,
        line: 1,
        lineText: 'import * as wasm from "./rapier_wasm2d_bg.wasm";',
        namespace: '',
        suggestion: ''
      },
      notes: [],
      pluginName: '',
      text: 'No loader is configured for ".wasm" files: node_modules/@dimforge/rapier2d/rapier_wasm2d_bg.wasm'
    }
  ],
  warnings: []
}```

Can't find any information about this error, anywhere.

**Comment by Menci** [comment]
I just figured out that Vite 3 use esbuild to optimize dependencies in dev server. Use this for a workaround:

```ts
{
  optimizeDeps: {
    exclude: [
      "@dimforge/rapier2d"
    ]
  }
}
```

With `{ optimizeDeps: { disabled: true } }` it works too but may slow down the preview performance.

Let's keep this issue open and I'll discuss with Vite upstream for this behavior.

**Comment by Menci** [comment]
https://github.com/vitejs/vite/discussions/9256

**Comment by Yaron-Ha** [comment]
> 

Welp, that didn't work. I added that fix and now I get a different error:
```
rapier_wasm2d_bg.js:4273 Uncaught ReferenceError: Cannot access 'memory' before initialization
    at rapier_wasm2d_bg.js:4273:46```
At runtime.

**Comment by Yaron-Ha** [comment]
> > 
> 
> Welp, that didn't work. I added that fix and now I get a different error:
> 
> ```
> rapier_wasm2d_bg.js:4273 Uncaught ReferenceError: Cannot access 'memory' before initialization
>     at rapier_wasm2d_bg.js:4273:46```
> At runtime.
> ```

https://github.com/dimforge/rapier.js/issues/49
Oh well. This appears to be the only thing that works

**Comment by Yaron-Ha** [comment]
https://github.com/dimforge/rapier.js/issues/49

This is the suggested fix, and it doesn't work.

**Comment by Menci** [comment]
https://github.com/rustwasm/wasm-bindgen/pull/2965

**Comment by AndrewJSchoen** [comment]
@Menci Not sure if this is the exact same issue, but I am encountering an error where the library I built with `wasm-bindgen` (I am using version `v0.2.83`) and the `bundler` target is failing to load and work within a web-worker. I followed the instructions in the readme, and you can see the example [here](https://codesandbox.io/p/sandbox/friendly-sid-whh2js?file=%2Fsrc%2Fworker-default.js). Specifically, you can see that if the import of the wasm library is included in the web worker file, it hangs, failing to execute anything. I thought this should be a fairly standard configuration, but haven't had any luck figuring it out. Any suggestions on what might be the issue here?
